version: '3'

services:
  web:
    image: web_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"

  bot:
    image: bot_image
    build: .
    command: python manage.py startbot
    volumes:
      - static_volume:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3
      - ./client.session:/app/client.session

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles

volumes:
  static_volume: