# Generated by Django 5.0.6 on 2024-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramBotToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Токен бота из BotFather",
                        max_length=255,
                        verbose_name="Токен бота",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Bot", max_length=255, verbose_name="Название бота"
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен бота",
                "verbose_name_plural": "Токены ботов",
            },
        ),
    ]
